# MONGO_DB_CONNECTION_STRING=
# ROOT_URL=
# EMAIL_NOTIFICATION=False
# EMAIL_USERNAME= //OPTIONAL
# EMAIL_PASSWORD= //OPTIONAL
# OPEN_AI_KEY= // OPTIONAL
# SIMULATION_EMAIL= // OPTIONAL
# SIMULATION_PASSWORD= // OPTIONAL